FROM python:3.10-slim


COPY ./app /app

RUN pip install -r /requirements.txt

EXPOSE 8000

ENV VARIABLE_1=value1
ENV VARIABLE_2=value2

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
